
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.tempuri.NcwsSoap;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ncws", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.130.241/ws/ncws.asmx?wsdl")
public class Ncws
    extends Service
{

    private final static URL NCWS_WSDL_LOCATION;
    private final static WebServiceException NCWS_EXCEPTION;
    private final static QName NCWS_QNAME = new QName("http://tempuri.org/", "ncws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.130.241/ws/ncws.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NCWS_WSDL_LOCATION = url;
        NCWS_EXCEPTION = e;
    }

    public Ncws() {
        super(__getWsdlLocation(), NCWS_QNAME);
    }

    public Ncws(WebServiceFeature... features) {
        super(__getWsdlLocation(), NCWS_QNAME, features);
    }

    public Ncws(URL wsdlLocation) {
        super(wsdlLocation, NCWS_QNAME);
    }

    public Ncws(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NCWS_QNAME, features);
    }

    public Ncws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ncws(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NcwsSoap
     */
    @WebEndpoint(name = "ncwsSoap")
    public NcwsSoap getNcwsSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ncwsSoap"), NcwsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NcwsSoap
     */
    @WebEndpoint(name = "ncwsSoap")
    public NcwsSoap getNcwsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ncwsSoap"), NcwsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NCWS_EXCEPTION!= null) {
            throw NCWS_EXCEPTION;
        }
        return NCWS_WSDL_LOCATION;
    }

}
